name = "ahms"
author = "clamling"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b31189c36bf5b10611e0f796c67989bc6788801de675c05721c31ae790be2166"

[versions]
fabric = "0.15.3"
minecraft = "1.19.2"
